# Generated by Django 3.1 on 2021-01-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210128_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('calories',)},
        ),
    ]
